### ISSUE TITLE
Isnt working with coc

### ISSUE THREAD

**Issue by mckenziewagner** [iamcco/coc-tailwindcss#2]
I'm unable to get this to work in my coc setup. Is there anything I need to know to get this to work? Are there anymore options I can set in CocConfig? I have a project with tailwindcss installed and I don't get any intellisense while editing.

**Comment by iamcco** [comment]
it need `tailwind init` general config in your project.

**Comment by mckenziewagner** [comment]
Ahh right on, thanks for getting back to me so quick and for creating this extension! Can I point the extension to where that file exists? Its not in the root of my project.

**Comment by mckenziewagner** [comment]
This was fixed by changing the placement of my tailwind.js config file to be in the root of my project. Thanks!

**Comment by AdrienLemaire** [comment]
@iamcco maybe you can add the `tailwind init` comment in the README? I discovered coc.nvim through your plugin (always used deoplete until now, and YouCompleteMe before that), and it took me a while to understand that the lack of completion was unrelated to my coc install, but to the missing tailwind.config.js.
Also, isn't there a way to parse the default config from `./node_models/tailwindcss/`? Because I have no need for a custom tailwind.config.js file in the root of my project.

**Comment by iamcco** [comment]
@AdrienLemaire I have updated readme
